# Generated by Django 4.0.3 on 2022-03-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('concat', models.IntegerField(help_text='please enter 10 digits')),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(blank=True, help_text='optional', max_length=200, null=True)),
            ],
        ),
    ]
