# Generated by Django 3.2.7 on 2022-03-10 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='concat',
            new_name='contact',
        ),
    ]
